services:
  server:
    container_name: kdf-wasm-rpc
    build:
      context: ./
      dockerfile: ./docker_files/Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    ports:
      - '${VITE_WS_PORT}:${VITE_WS_PORT}'
      - '${VITE_RPC_PORT}:${VITE_RPC_PORT}'
      - '${VITE_WEB_PORT}:${VITE_WEB_PORT}'
    volumes:
      - .:/home/kdfuser/app
