services:
  server:
    container_name: kdf-wasm-rpc
    build:
      context: ./
      dockerfile: ./docker_files/Dockerfile
    ports:
      - '${VITE_WS_PORT}:${VITE_WS_PORT}'
      - '${VITE_RPC_PORT}:${VITE_RPC_PORT}'
      - '${VITE_WEB_PORT}:${VITE_WEB_PORT}'
    volumes:
      - .:/app
      - kdf-rpc-node_modules:/app/node_modules
volumes:
  kdf-rpc-node_modules: {}
